#
#   @file : dependabot.yml
#   @date : 22 February 2022
#   @authors : Orel Adivi
#
# Dependabot - Security

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/firmware"
    schedule:
      interval: "weekly"
